<?php

namespace Database\Factories;

use App\Models\Company;
use Illuminate\Database\Eloquent\Factories\Factory;
use Ybazli\Faker\Facades\Faker;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\TransportContract>
 */
class TransportContractFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {

        return [
            'panel_code' => Company::inRandomOrder()->first()->panel_code,
            'ContractNumber' => fake()->numerify('#########'),
            'ContractTitle' => Faker::word(),
            'ContractDate' => fake()->iso8601(),
            'CommissionPercent' => fake()->randomFloat(2,4,99),
            'Customer' => Faker::firstName(),
            'ComplementaryPercent' => fake()->randomFloat(2,4,99),
            'TerminalCommission' => fake()->randomFloat(2,4,99),
            'Description' => Faker::paragraph(),
            'IsActive' => fake()->boolean(),
            'IsContractDefault' => fake()->boolean(),
            'IsDefault_N0' => fake()->numberBetween(0, 3),
            'IsDefault_N1' => fake()->numberBetween(0, 3),
            'IsDefault_N2' => fake()->numberBetween(0, 3),
            'IsDefault_N3' => fake()->numberBetween(0, 3),
            'AfterDelivered' => getRandomCost(6),
            'N0_BaseFreight' => fake()->boolean(),
            'N0_PreFreight' => fake()->boolean(),
            'N0_RemFreight' => fake()->boolean(),
            'N0_Sleep' => fake()->boolean(),
            'N0_commission' => fake()->boolean(),
            'N0_Storage' => fake()->boolean(),
            'N0_Terminal' => fake()->boolean(),
            'N0_Scale' => fake()->boolean(),
            'N0_Insurance' => fake()->boolean(),
            'N0_Tonnage' => fake()->boolean(),
            'N0_Loading' => fake()->boolean(),
            'N0_Tax' => fake()->boolean(),
            'N0_InsuranceTax' => fake()->boolean(),
            'N0_TakeFromDriver' => fake()->boolean(),
            'N0_Stamp' => fake()->boolean(),
            'N0_TraceCode' => fake()->boolean(),
            'N0_Deductions' => fake()->boolean(),
            'N0_Antiseptic' => fake()->boolean(),
            'N0_Elambar' => fake()->boolean(),
            'N0_Unload' => fake()->boolean(),
            'N0_Complementary' => fake()->boolean(),
            'N1_BaseFreight' => fake()->boolean(),
            'N1_PreFreight' => fake()->boolean(),
            'N1_RemFreight' => fake()->boolean(),
            'N1_Sleep' => fake()->boolean(),
            'N1_commission' => fake()->boolean(),
            'N1_Storage' => fake()->boolean(),
            'N1_Terminal' => fake()->boolean(),
            'N1_Scale' => fake()->boolean(),
            'N1_Insurance' => fake()->boolean(),
            'N1_Tonnage' => fake()->boolean(),
            'N1_Loading' => fake()->boolean(),
            'N1_Tax' => fake()->boolean(),
            'N1_InsuranceTax' => fake()->boolean(),
            'N1_TakeFromDriver' => fake()->boolean(),
            'N1_Stamp' => fake()->boolean(),
            'N1_TraceCode' => fake()->boolean(),
            'N1_Deductions' => fake()->boolean(),
            'N1_Antiseptic' => fake()->boolean(),
            'N1_Elambar' => fake()->boolean(),
            'N1_Unload' => fake()->boolean(),
            'N1_Complementary' => fake()->boolean(),
            'N2_BaseFreight' => fake()->boolean(),
            'N2_PreFreight' => fake()->boolean(),
            'N2_RemFreight' => fake()->boolean(),
            'N2_Sleep' => fake()->boolean(),
            'N2_commission' => fake()->boolean(),
            'N2_Storage' => fake()->boolean(),
            'N2_Terminal' => fake()->boolean(),
            'N2_Scale' => fake()->boolean(),
            'N2_Insurance' => fake()->boolean(),
            'N2_Tonnage' => fake()->boolean(),
            'N2_Loading' => fake()->boolean(),
            'N2_Tax' => fake()->boolean(),
            'N2_InsuranceTax' => fake()->boolean(),
            'N2_TakeFromDriver' => fake()->boolean(),
            'N2_Stamp' => fake()->boolean(),
            'N2_TraceCode' => fake()->boolean(),
            'N2_Deductions' => fake()->boolean(),
            'N2_Antiseptic' => fake()->boolean(),
            'N2_Elambar' => fake()->boolean(),
            'N2_Unload' => fake()->boolean(),
            'N2_Complementary' => fake()->boolean(),
            'N3_BaseFreight' => fake()->boolean(),
            'N3_PreFreight' => fake()->boolean(),
            'N3_RemFreight' => fake()->boolean(),
            'N3_Sleep' => fake()->boolean(),
            'N3_commission' => fake()->boolean(),
            'N3_Storage' => fake()->boolean(),
            'N3_Terminal' => fake()->boolean(),
            'N3_Scale' => fake()->boolean(),
            'N3_Insurance' => fake()->boolean(),
            'N3_Tonnage' => fake()->boolean(),
            'N3_Loading' => fake()->boolean(),
            'N3_Tax' => fake()->boolean(),
            'N3_InsuranceTax' => fake()->boolean(),
            'N3_TakeFromDriver' => fake()->boolean(),
            'N3_Stamp' => fake()->boolean(),
            'N3_TraceCode' => fake()->boolean(),
            'N3_Deductions' => fake()->boolean(),
            'N3_Antiseptic' => fake()->boolean(),
            'N3_Elambar' => fake()->boolean(),
            'N3_Unload' => fake()->boolean(),
            'N3_Complementary' => fake()->boolean(),
            'def_Sleep' => getRandomCost(5),
            'def_Storage' => getRandomCost(5),
            'def_Scale' => getRandomCost(5),
            'def_Insurance' => getRandomCost(5),
            'def_Tonnage' => getRandomCost(5),
            'def_Loading' => getRandomCost(5),
            'def_InsuranceTax' => getRandomCost(5),
            'def_TakeFromDriver' => getRandomCost(5),
            'def_Stamp' => getRandomCost(5),
            'def_TraceCode' => getRandomCost(5),
            'def_Antiseptic' => getRandomCost(5),
            'def_Elambar' => getRandomCost(5),
            'def_Unload' => getRandomCost(5),
            'R_BaseFreight' => fake()->boolean() ,
            'R_PreFreight' => fake()->boolean() ,
            'R_RemFreight' => fake()->boolean() ,
            'R_Sleep' => fake()->boolean() ,
            'R_Commission' => fake()->boolean() ,
            'R_Storage' => fake()->boolean() ,
            'R_Terminal' => fake()->boolean() ,
            'R_Scale' => fake()->boolean() ,
            'R_Insurance' => fake()->boolean() ,
            'R_Tonnage' => fake()->boolean() ,
            'R_Loading' => fake()->boolean() ,
            'R_Tax' => fake()->boolean() ,
            'R_InsuranceTax' => fake()->boolean() ,
            'R_TakeFromDriver' => fake()->boolean() ,
            'R_Stamp' => fake()->boolean() ,
            'R_TraceCode' => fake()->boolean() ,
            'R_Deductions' => fake()->boolean() ,
            'R_Antiseptic' => fake()->boolean() ,
            'R_Elambar' => fake()->boolean() ,
            'R_Unload' => fake()->boolean() ,
            'R_Complementary' => fake()->boolean() ,
        ];
    }
}
