<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Casts\Set;

class TransportContract extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $casts = [
        'IsActive' => 'boolean',
        'IsContractDefault' => 'boolean',
        'ContractDate' => 'datetime',
        'N0_BaseFreight' => 'boolean',
        'N0_PreFreight' => 'boolean',
        'N0_RemFreight' => 'boolean',
        'N0_Sleep' => 'boolean',
        'N0_commission' => 'boolean',
        'N0_Storage' => 'boolean',
        'N0_Terminal' => 'boolean',
        'N0_Scale' => 'boolean',
        'N0_Insurance' => 'boolean',
        'N0_Tonnage' => 'boolean',
        'N0_Loading' => 'boolean',
        'N0_Tax' => 'boolean',
        'N0_InsuranceTax' => 'boolean',
        'N0_TakeFromDriver' => 'boolean',
        'N0_Stamp' => 'boolean',
        'N0_TraceCode' => 'boolean',
        'N0_Deductions' => 'boolean',
        'N0_Antiseptic' => 'boolean',
        'N0_Elambar' => 'boolean',
        'N0_Unload' => 'boolean',
        'N0_Complementary' => 'boolean',
        'N1_BaseFreight' => 'boolean',
        'N1_PreFreight' => 'boolean',
        'N1_RemFreight' => 'boolean',
        'N1_Sleep' => 'boolean',
        'N1_commission' => 'boolean',
        'N1_Storage' => 'boolean',
        'N1_Terminal' => 'boolean',
        'N1_Scale' => 'boolean',
        'N1_Insurance' => 'boolean',
        'N1_Tonnage' => 'boolean',
        'N1_Loading' => 'boolean',
        'N1_Tax' => 'boolean',
        'N1_InsuranceTax' => 'boolean',
        'N1_TakeFromDriver' => 'boolean',
        'N1_Stamp' => 'boolean',
        'N1_TraceCode' => 'boolean',
        'N1_Deductions' => 'boolean',
        'N1_Antiseptic' => 'boolean',
        'N1_Elambar' => 'boolean',
        'N1_Unload' => 'boolean',
        'N1_Complementary' => 'boolean',
        'N2_BaseFreight' => 'boolean',
        'N2_PreFreight' => 'boolean',
        'N2_RemFreight' => 'boolean',
        'N2_Sleep' => 'boolean',
        'N2_commission' => 'boolean',
        'N2_Storage' => 'boolean',
        'N2_Terminal' => 'boolean',
        'N2_Scale' => 'boolean',
        'N2_Insurance' => 'boolean',
        'N2_Tonnage' => 'boolean',
        'N2_Loading' => 'boolean',
        'N2_Tax' => 'boolean',
        'N2_InsuranceTax' => 'boolean',
        'N2_TakeFromDriver' => 'boolean',
        'N2_Stamp' => 'boolean',
        'N2_TraceCode' => 'boolean',
        'N2_Deductions' => 'boolean',
        'N2_Antiseptic' => 'boolean',
        'N2_Elambar' => 'boolean',
        'N2_Unload' => 'boolean',
        'N2_Complementary' => 'boolean',
        'N3_BaseFreight' => 'boolean',
        'N3_PreFreight' => 'boolean',
        'N3_RemFreight' => 'boolean',
        'N3_Sleep' => 'boolean',
        'N3_commission' => 'boolean',
        'N3_Storage' => 'boolean',
        'N3_Terminal' => 'boolean',
        'N3_Scale' => 'boolean',
        'N3_Insurance' => 'boolean',
        'N3_Tonnage' => 'boolean',
        'N3_Loading' => 'boolean',
        'N3_Tax' => 'boolean',
        'N3_InsuranceTax' => 'boolean',
        'N3_TakeFromDriver' => 'boolean',
        'N3_Stamp' => 'boolean',
        'N3_TraceCode' => 'boolean',
        'N3_Deductions' => 'boolean',
        'N3_Antiseptic' => 'boolean',
        'N3_Elambar' => 'boolean',
        'N3_Unload' => 'boolean',
        'N3_Complementary' => 'boolean',
        'R_BaseFreight' => 'boolean',
        'R_PreFreight' => 'boolean',
        'R_RemFreight' => 'boolean',
        'R_Sleep' => 'boolean',
        'R_Commission' => 'boolean',
        'R_Storage' => 'boolean',
        'R_Terminal' => 'boolean',
        'R_Scale' => 'boolean',
        'R_Insurance' => 'boolean',
        'R_Tonnage' => 'boolean',
        'R_Loading' => 'boolean',
        'R_Tax' => 'boolean',
        'R_InsuranceTax' => 'boolean',
        'R_TakeFromDriver' => 'boolean',
        'R_Stamp' => 'boolean',
        'R_TraceCode' => 'boolean',
        'R_Deductions' => 'boolean',
        'R_Antiseptic' => 'boolean',
        'R_Elambar' => 'boolean',
        'R_Unload' => 'boolean',
        'R_Complementary' => 'boolean',
    ];
}
